---
- name: Check if Bitwarden CLI is installed
  command: which bw
  register: bw_check
  changed_when: false
  failed_when: false

- name: Set brew binary path
  set_fact:
    brew_bin: "{{ '/opt/homebrew/bin/brew' if ansible_os_family == 'Darwin' else '/home/linuxbrew/.linuxbrew/bin/brew' }}"
  when: bw_check.rc != 0

- name: Install Bitwarden CLI via Homebrew
  community.general.homebrew:
    name: bitwarden-cli
    state: present
  environment:
    PATH: "{{ brew_bin | dirname }}:{{ ansible_facts.env.PATH }}"
  when: bw_check.rc != 0
